
- name: check for updates
  hosts: all
  gather_facts: true
#  user: root

  tasks:

  - name: install yum-utils if not already installed
    yum:
      name: yum-utils
      state: latest

  - name: check for updates (yum)
    yum: list=updates update_cache=true
    register: yumoutput
    #when: ansible_distribution_major_version|int < 22

  # - name: check for updates (apt)
  #   apt: list=updates update_cache=true
  #   register: aptoutput
  #   when: ansible_distribution_major_version|int < 22

  - debug: msg="{{ inventory_hostname}} {{ yumoutput.results|length }}"
    when: yumoutput is defined and yumoutput.results|length > 0
  #
  # - debug: msg="{{ inventory_hostname}} {{ yumoutput.results|length }}"
  #   when: aptoutput is defined and aptoutput.results|length > 0
