- name: Update hosts with all the latest packages
  hosts: all


  tasks:
  - name: run the yum updater
    #action: yum -a "name='*' state=latest"
    yum: name='*' state=latest
    only_if: "'$ansible_pkg_mgr' == 'yum'"

  # - name: run the apt-get updater
  #   action: apt -a "upgrade=yes update_cache=yes" -s
  #   only_if: "'$ansible_pkg_mgr' == 'apt'"
