- name: Update hosts with all the latest packages
  hosts: all
  become: sudo


  tasks:
    - name: run the yum updater
      yum:
        name: '*'
        state: latest
        only_if: "'$ansible_pkg_mgr' == 'yum'"

    - name: run the apt-get updater
      apt:
        name: '*'
        state: latest
        only_if: "'$ansible_pkg_mgr' == 'apt'"
